Update pipeline githubbugcheck

diff --git a/.harness/github.yaml b/.harness/github.yaml
--- a/.harness/github.yaml
+++ b/.harness/github.yaml
@@ -23,30 +23,41 @@ pipeline:
                     source:
                       type: Inline
                       spec:
-                        script: |+
-                          #!/bin/bash
+                        script: |
+                          # #!/bin/bash
 
-                          # Check if Git is installed
-                          if command -v git &> /dev/null; then
-                              echo "Git is already installed."
-                          else
-                              echo "Git not found. Installing Git..."
+                          # # Check if Git is installed
+                          # if command -v git &> /dev/null; then
+                          #     echo "Git is already installed."
+                          # else
+                          #     echo "Git not found. Installing Git..."
 
-                              # Update the system and install required dependencies
-                              sudo yum update -y
+                          #     # Update the system and install required dependencies
+                          #     sudo yum update -y
 
-                              # Install Git using YUM
-                              sudo yum install git -y
+                          #     # Install Git using YUM
+                          #     sudo yum install git -y
 
-                              # Verify Git installation
+                          #     # Verify Git installation
+                          #     if command -v git &> /dev/null; then
+                          #         echo "Git installed successfully."
+                          #     else
+                          #         echo "Error: Git installation failed."
+                          #         exit 1
+                          #     fi
+                          # fi
+
+
+
+                          microdnf install git -y
+
+                              # Verify installation
                               if command -v git &> /dev/null; then
                                   echo "Git installed successfully."
                               else
                                   echo "Error: Git installation failed."
                                   exit 1
                               fi
-                          fi
-
                     environmentVariables: []
                     outputVariables: []
                   timeout: 10m
